name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 79.143.90.73 >> ~/.ssh/known_hosts

      # Desplegar Backend Node
      - name: Deploy backend (Node.js)
        run: |
          rsync -avz --delete ./back/ root@79.143.90.73:/root/node
          ssh root@79.143.90.73 << 'EOF'
            cd /root/node
            npm install
            pm2 restart backend || pm2 start app.js --name backend
          EOF

      # Desplegar Frontend Nuxt
      - name: Deploy frontend (Nuxt)
        run: |
          cd front
          npm install
          npm run generate
          rsync -avz --delete ./dist/ root@79.143.90.73:/var/www/html
          ssh root@79.143.90.73 "systemctl restart nginx || systemctl restart apache2"
